version: '3'
services:
  socket-runner-server:
    image: socket-runner:latest
    container_name: socket-runner-server
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    ports:
      - "1000-1019:1000-1019"
      - "60000:60000"
    networks:
      - socket-runner
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GEVENT_SUPPORT=True
      - tcp_host=0.0.0.0
      - tcp_port=1000-1009
      - udp_host=0.0.0.0
      - udp_port=1010-1019
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:60000", "server.py"]

  socket-runner-client:
    image: socket-runner:latest
    container_name: socket-runner-client
    build:
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 6G
    ports:
      - "60001:60001"
    networks:
      - socket-runner
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - GEVENT_SUPPORT=True
      - tcp_host=socket-runner-server
      - tcp_port=1000
      - udp_host=socket-runner-server
      - udp_port=1010
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:60001", "--wait-for-client", "client.py"]

networks:
  socket-runner:
    driver: bridge